apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-01-07T20:37:00Z
  name: base.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  kubeAPIServer:
    authorizationRbacSuperUser: admin
  channel: stable
  cloudProvider: gce
  configBase: gs://kops-cluster-store/base.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west1-a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west1-a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.6
  masterPublicName: api.base.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: k8s-builder
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: us-west1
    region: us-west1
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
