- name: Local thing
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Set ETCD hosts
      debug:
        msg: "{{ groups['tag_etcd'] | map('regex_replace', '(.*)?', 'http://\\1:2379') | list | join(',') }}"
    - name: Save token
      set_fact:
        master_token: "testto.kenfor0123456789"


- name: Bootstrap Master
  hosts: tag_master
  become: yes

  vars_files:
    - vars.yml

  environment:
    BOOTSTRAP_TOKEN: "{{ hostvars['localhost']['master_token'] }}"
    ETCD_IPS: "{{ groups['tag_etcd'] | map('regex_replace', '(.*)?', 'http://\\1:2379') | list | join(',')  }}"

  roles:
    - k8s_master

- name: Bootstrap Nodes
  hosts: tag_worker
  gather_facts: yes
  become: yes

  environment:
    K8S_MASTER_IP: "{{ groups['tag_master'] | join('') }}"
    BOOTSTRAP_TOKEN: "{{ hostvars['localhost']['master_token'] }}"

  roles:
    - k8s_worker
